using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace Nullean.Argh;

public sealed partial class CliParserGenerator
{
	private static string GetArghGeneratedRootTypeName(string assemblyName)
	{
		using var sha = SHA256.Create();
		var h = sha.ComputeHash(Encoding.UTF8.GetBytes(assemblyName));
		return "ArghGenerated_" + BitConverter.ToString(h, 0, 4).Replace("-", "");
	}

	private static string? TryGetStringConstant(SemanticModel model, ExpressionSyntax expr)
	{
		var lit = TryGetStringLiteral(expr);
		if (lit is not null)
			return lit;
		var cv = model.GetConstantValue(expr);
		if (cv.HasValue && cv.Value is string s)
			return s;
		return null;
	}

	private static void EmitNamespaceSegmentCodegen(SourceProductionContext context, AppEmitModel app)
	{
		if (app.ArglessNamespaceCodegen.Count == 0)
			return;

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using Nullean.Argh;");
		sb.AppendLine();
		sb.AppendLine("internal static class ArghNamespaceSegmentInitializer");
		sb.AppendLine("{");
		sb.AppendLine("	[System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("	internal static void Init()");
		sb.AppendLine("	{");
		foreach (var e in app.ArglessNamespaceCodegen)
		{
			var escaped = e.Segment.Replace("\\", "\\\\").Replace("\"", "\\\"");
			sb.AppendLine("\t\tglobal::Nullean.Argh.ArghNamespaceSegmentCodegen.Set<" + e.TypeFq + ">(\"" + escaped + "\");");
		}
		sb.AppendLine("	}");
		sb.AppendLine("}");
		context.AddSource("ArghNamespaceSegmentInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
	}


	private static void EmitEmpty(SourceProductionContext context, string assemblyName, string assemblyVersion)
	{
		const string source = """
			// <auto-generated/>
			#nullable enable
			using System;
			using System.Threading.Tasks;
			using Nullean.Argh.Middleware;
			using Nullean.Argh.Help;
			using Nullean.Argh.Matching;
			using Nullean.Argh.Runtime;
			using Nullean.Argh.Schema;

			namespace Nullean.Argh
			{
				/// <summary>Source-generated CLI entry point from <c>ArghApp</c> registrations. At the root, <c>__completion bash|zsh|fish</c> prints a shell script from <see cref="global::Nullean.Argh.Help.CompletionScriptTemplates"/>.</summary>
				public static class ArghGenerated
				{
					public static Task<int> RunAsync(string[] args) =>
						Task.FromResult(Run(args));

					public static bool TryParseRoute(string[] args, out RouteMatch match)
					{
						match = default;
						if (CompletionProtocol.IsArghMetaCompletionInvocation(args))
							return false;
						return false;
					}

					public static RouteMatch? Route(string[] args)
					{
						if (args is null)
							throw new ArgumentNullException(nameof(args));
						if (!TryParseRoute(args, out var m))
							return null;
						return m;
					}

					private static int Run(string[] args)
					{
						if (CompletionProtocol.IsCompletionScriptInvocation(args))
						{
							if (!CompletionProtocol.TryParseCompletionScriptInvocation(args, out var __scriptShell))
							{
								System.Console.Error.WriteLine("Error: expected '__completion bash|zsh|fish'");
								return 2;
							}
							var appName = "__ARGH_EMBED_ASM_NAME__";
							switch (__scriptShell)
							{
								case CompletionShell.Bash:
									System.Console.Out.Write(CompletionScriptTemplates.GetBash().Replace("{0}", appName));
									return 0;
								case CompletionShell.Zsh:
									System.Console.Out.Write(CompletionScriptTemplates.GetZsh().Replace("{0}", appName));
									return 0;
								case CompletionShell.Fish:
									System.Console.Out.Write(CompletionScriptTemplates.GetFish().Replace("{0}", appName));
									return 0;
								default:
									return 2;
							}
						}

						if (CompletionProtocol.IsCompleteInvocation(args))
						{
							if (!CompletionProtocol.TryParseCompleteInvocation(args, out _, out var __words))
							{
								System.Console.Error.WriteLine("Error: expected '__complete <bash|zsh|fish> -- [words...]'");
								return 2;
							}
							Complete(default, __words);
							return 0;
						}

						if (CompletionProtocol.IsSchemaInvocation(args))
						{
							System.Console.Out.Write(ArghRuntime.FormatCliSchemaJson());
							return 0;
						}

						if (args.Length > 0 && (args[0] == "--help" || args[0] == "-h"))
						{
							System.Console.Out.WriteLine("No commands are registered.");
							return 0;
						}

						if (args.Length > 0 && args[0] == "--version")
						{
							PrintVersion();
							return 0;
						}

						System.Console.Error.WriteLine("No commands are registered.");
						return 2;
					}

					private static void Complete(CompletionShell shell, ReadOnlySpan<string> words)
					{
						_ = shell;
						_ = words;
					}

					private static void PrintVersion()
					{
						System.Console.Out.WriteLine("__ARGH_EMBED_ASM_VER__");
					}

					internal static bool IsIntrinsicCommand(string[] args) => false;

					internal static ArghCliSchemaDocument BuildCliSchemaDocument() =>
						new ArghCliSchemaDocument(
							1,
							"__ARGH_EMBED_ASM_NAME__",
							"__ARGH_EMBED_ASM_VER__",
							null,
							new[] { "__complete", "__completion", "__schema" },
							Array.Empty<CliParameterSchema>(),
							null,
							Array.Empty<CliCommandSchema>(),
							Array.Empty<CliNamespaceSchema>());
				}

				internal static class ArghGeneratedRuntimeRegistration
				{
					[System.Runtime.CompilerServices.ModuleInitializer]
					internal static void RegisterArghRuntime()
					{
						ArghRuntime.RegisterRunner(ArghGenerated.RunAsync);
						ArghRuntime.RegisterRoute(ArghGenerated.Route);
						ArghRuntime.RegisterCliSchema(ArghGenerated.BuildCliSchemaDocument);
						ArghRuntime.RegisterIntrinsic(ArghGenerated.IsIntrinsicCommand);
					}
				}
			}
			""";
		var root = GetArghGeneratedRootTypeName(assemblyName);
		var resolved = source
			.Replace("__ARGH_EMBED_ASM_NAME__", Escape(assemblyName))
			.Replace("__ARGH_EMBED_ASM_VER__", Escape(assemblyVersion))
			.Replace("internal static class ArghGeneratedRuntimeRegistration", "internal static class " + root + "RuntimeRegistration")
			.Replace("public static class ArghGenerated", "public static class " + root)
			.Replace("ArghGenerated.", root + ".");
		context.AddSource("ArghGenerated.g.cs", SourceText.From(resolved, Encoding.UTF8));
	}


	private static void AppendArghRuntimeModuleInitializer(StringBuilder sb, string rootTypeName)
	{
		sb.AppendLine();
		sb.AppendLine("\tinternal static class " + rootTypeName + "RuntimeRegistration");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\t[System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("\t\tinternal static void RegisterArghRuntime()");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tArghRuntime.RegisterRunner(" + rootTypeName + ".RunAsync);");
		sb.AppendLine("\t\t\tArghRuntime.RegisterRoute(" + rootTypeName + ".Route);");
		sb.AppendLine("\t\t\tArghRuntime.RegisterCliSchema(" + rootTypeName + ".BuildCliSchemaDocument);");
		sb.AppendLine("\t\t\tArghRuntime.RegisterIntrinsic(" + rootTypeName + ".IsIntrinsicCommand);");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private const int FuzzyMaxDistance = 2;

	private static void EmitRootCompletionScriptBlock(StringBuilder sb, string indent, string entryAssemblyName)
	{
		sb.AppendLine(indent + "if (CompletionProtocol.IsCompletionScriptInvocation(args))");
		sb.AppendLine(indent + "{");
		sb.AppendLine(indent + "\tif (!CompletionProtocol.TryParseCompletionScriptInvocation(args, out var __scriptShell))");
		sb.AppendLine(indent + "\t{");
		sb.AppendLine(indent + "\t\tConsole.Error.WriteLine(\"Error: expected '__completion bash|zsh|fish'\");");
		sb.AppendLine(indent + "\t\treturn 2;");
		sb.AppendLine(indent + "\t}");
		sb.AppendLine(indent + "\tvar __entry = \"" + Escape(entryAssemblyName) + "\";");
		sb.AppendLine(indent + "\tswitch (__scriptShell)");
		sb.AppendLine(indent + "\t{");
		sb.AppendLine(indent + "\t\tcase CompletionShell.Bash:");
		sb.AppendLine(indent + "\t\t\tConsole.Out.Write(CompletionScriptTemplates.GetBash().Replace(\"{0}\", __entry));");
		sb.AppendLine(indent + "\t\t\treturn 0;");
		sb.AppendLine(indent + "\t\tcase CompletionShell.Zsh:");
		sb.AppendLine(indent + "\t\t\tConsole.Out.Write(CompletionScriptTemplates.GetZsh().Replace(\"{0}\", __entry));");
		sb.AppendLine(indent + "\t\t\treturn 0;");
		sb.AppendLine(indent + "\t\tcase CompletionShell.Fish:");
		sb.AppendLine(indent + "\t\t\tConsole.Out.Write(CompletionScriptTemplates.GetFish().Replace(\"{0}\", __entry));");
		sb.AppendLine(indent + "\t\t\treturn 0;");
		sb.AppendLine(indent + "\t\tdefault:");
		sb.AppendLine(indent + "\t\t\treturn 2;");
		sb.AppendLine(indent + "\t}");
		sb.AppendLine(indent + "}");
		sb.AppendLine();
	}


	private static void EmitFuzzyDispatchDefault(
		StringBuilder sb,
		RegistryNode node,
		ImmutableArray<string> path,
		string entryAssemblyName)
	{
		var entries = new List<(string Name, string Summary, string HelpPrinter)>();
		foreach (var cmd in node.Commands)
			entries.Add((cmd.CommandName, cmd.SummaryOneLiner, $"PrintHelp_{cmd.RunMethodName}"));
		foreach (var ch in node.Children)
		{
			var childPath = AppendSegment(path, ch.Segment);
			var gk = CommandNamespacePathKey(childPath);
			entries.Add((ch.Segment, "", $"PrintHelp_CommandNamespace_{gk}"));
		}

		var sorted =
			entries.OrderBy(e => e.Name, StringComparer.Ordinal).ToList();

		var pathPrefix = path.IsDefaultOrEmpty ? "" : string.Join(" ", path) + " ";
		var nsHelp = path.IsDefaultOrEmpty ? "--help" : Escape(string.Join(" ", path)) + " --help";

		sb.AppendLine("\t\t\t\tvar __tok = tok;");
		sb.AppendLine("\t\t\t\tvar __app = \"" + Escape(entryAssemblyName) + "\";");
		sb.Append("\t\t\t\tvar __cands = new string[] { ");
		for (var i = 0; i < sorted.Count; i++)
		{
			if (i > 0)
				sb.Append(", ");
			sb.Append('"').Append(Escape(sorted[i].Name)).Append('"');
		}

		sb.AppendLine(" };");
		sb.AppendLine($"\t\t\t\tvar __matches = FuzzyMatch.FindClosest(__tok, __cands, {FuzzyMaxDistance});");
		const string kind = "command or namespace";
		sb.AppendLine("\t\t\t\tif (__matches.Count == 0)");
		sb.AppendLine("\t\t\t\t{");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Error: unknown {kind} '{{__tok}}'.\");");
		sb.AppendLine("\t\t\t\t\tConsole.Error.WriteLine();");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Run '{{__app}} {nsHelp}' for usage.\");");
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t\telse if (__matches.Count == 1)");
		sb.AppendLine("\t\t\t\t{");
		sb.AppendLine("\t\t\t\t\tvar __m = __matches[0];");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Error: unknown {kind} '{{__tok}}'. Did you mean '{Escape(pathPrefix)}{{__m}}'?\");");
		sb.AppendLine("\t\t\t\t\tConsole.Error.WriteLine();");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Run '{{__app}} {Escape(pathPrefix)}{{__m}} --help' for usage.\");");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Run '{{__app}} {nsHelp}' for usage.\");");
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t\telse");
		sb.AppendLine("\t\t\t\t{");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Error: unknown {kind} '{{__tok}}'. Did you mean one of these?\");");
		sb.AppendLine("\t\t\t\t\tConsole.Error.WriteLine();");
		foreach (var e in sorted)
		{
			var qualifiedName = Escape(pathPrefix + e.Name);
			var sum = Escape(e.Summary);
			sb.AppendLine(
				$"\t\t\t\t\tif (__matches.Any(__x => string.Equals(__x, \"{Escape(e.Name)}\", StringComparison.OrdinalIgnoreCase)))");
			sb.AppendLine("\t\t\t\t\t{");
			sb.AppendLine(
				$"\t\t\t\t\t\tConsole.Error.WriteLine(\"  \" + CliHelpFormatting.Accent(\"{qualifiedName}\") + \"    {sum}\");");
			sb.AppendLine("\t\t\t\t\t}");
		}

		sb.AppendLine("\t\t\t\t\tConsole.Error.WriteLine();");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Run '{{__app}} {Escape(pathPrefix)}<command> --help' for usage.\");");
		sb.AppendLine($"\t\t\t\t\tConsole.Error.WriteLine($\"Run '{{__app}} {nsHelp}' for usage.\");");
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t\treturn 2;");
	}


	private static void AppendRunWithCancellationAsyncMethod(StringBuilder sb)
	{
		sb.AppendLine("\t\tprivate static async Task<int> RunWithCancellationAsync(string[] args)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tusing var cts = new CancellationTokenSource();");
		sb.AppendLine("\t\t\tConsole.CancelKeyPress += (_, e) => { e.Cancel = true; cts.Cancel(); };");
		sb.AppendLine("\t\t\tCancellationTokenSource? __linkedCts = null;");
		sb.AppendLine("\t\t\ttry");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tCancellationToken ct = cts.Token;");
		sb.AppendLine("\t\t\t\tif (ArghHostRuntime.ApplicationStopping is CancellationToken __hostStopping)");
		sb.AppendLine("\t\t\t\t{");
		sb.AppendLine("\t\t\t\t\t__linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cts.Token, __hostStopping);");
		sb.AppendLine("\t\t\t\t\tct = __linkedCts.Token;");
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t\treturn await RunCoreAsync(args, ct).ConfigureAwait(false);");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tcatch (Exception ex)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tConsole.Error.WriteLine(ex.ToString());");
		sb.AppendLine("\t\t\t\treturn 1;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tfinally");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\t__linkedCts?.Dispose();");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
	}

	/// <summary>
	/// Returns <see langword="true"/> if the method or its containing type carries
	/// <c>[NoOptionsInjection]</c>, suppressing AGH0021 and handler-level options-parameter requirements.
	/// Globals/namespaced flags still splice as <see cref="ParameterKind.OptionsInjected"/> for parsing/reconstruction.
	/// </summary>
	private static bool HasNoOptionsInjection(IMethodSymbol method)
	{
		const string attrName = "NoOptionsInjectionAttribute";
		const string ns = "Nullean.Argh";
		foreach (var a in method.GetAttributes())
			if (a.AttributeClass?.Name == attrName && a.AttributeClass.ContainingNamespace?.ToDisplayString() == ns)
				return true;
		foreach (var a in method.ContainingType.GetAttributes())
			if (a.AttributeClass?.Name == attrName && a.AttributeClass.ContainingNamespace?.ToDisplayString() == ns)
				return true;
		return false;
	}

	private static bool HasPublicParameterlessCtor(INamedTypeSymbol type)
	{
		foreach (var ctor in type.InstanceConstructors)
		{
			if (ctor.Parameters.Length == 0 && ctor.DeclaredAccessibility == Accessibility.Public)
				return true;
		}

		return false;
	}

	private static string DiResolveOrNew(string fullyQualifiedType, bool allowParameterlessFallback)
	{
		if (allowParameterlessFallback)
			return $"((ArghServices.ServiceProvider?.GetService(typeof({fullyQualifiedType})) as {fullyQualifiedType}) ?? new {fullyQualifiedType}())";

		return
			$"((ArghServices.ServiceProvider?.GetService(typeof({fullyQualifiedType})) as {fullyQualifiedType}) ?? throw new global::System.InvalidOperationException(\"Register the type in DI for hosted execution, or add a public parameterless constructor for standalone CLI.\"))";
	}

	private static void EmitApp(
		SourceProductionContext context,
		AppEmitModel app,
		CSharpParseOptions parseOptions,
		string entryAssemblyName,
		string entryAssemblyVersion,
		string entrySchemaVersion,
		ReferenceMetadataCapabilities.Capabilities referenceCapabilities)
	{
		_ = referenceCapabilities;
		_ = parseOptions;  // no longer needed for DTO building; kept in signature for future use
		var dtoTargets = CollectDtoBindingTargets(app);
		var root = GetArghGeneratedRootTypeName(entryAssemblyName);
		EmitHierarchical(context, app, dtoTargets, entryAssemblyName, entryAssemblyVersion, entrySchemaVersion, root);
		EmitDtoTypeExtensions(context, dtoTargets, root);
	}

	private static void EmitHierarchical(
		SourceProductionContext context,
		AppEmitModel app,
		ImmutableArray<DtoBindingTarget> dtoTargets,
		string entryAssemblyName,
		string entryAssemblyVersion,
		string entrySchemaVersion,
		string arghGeneratedRootTypeName)
	{
		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine("using System.Globalization;");
		sb.AppendLine("using System.IO;");
		sb.AppendLine("using System.Linq;");
		sb.AppendLine("using System.Threading;");
		sb.AppendLine("using System.Threading.Tasks;");
		sb.AppendLine("using Nullean.Argh.Middleware;");
		sb.AppendLine("using Nullean.Argh.Help;");
		sb.AppendLine("using Nullean.Argh.Matching;");
		sb.AppendLine("using Nullean.Argh.Runtime;");
		sb.AppendLine("using Nullean.Argh.Schema;");
		sb.AppendLine();
		sb.AppendLine("namespace Nullean.Argh");
		sb.AppendLine("{");
		sb.AppendLine("\t/// <summary>Source-generated CLI entry point from <c>ArghApp</c> registrations. At the root, <c>__completion bash|zsh|fish</c> prints a shell script from <see cref=\"global::Nullean.Argh.Help.CompletionScriptTemplates\"/>; each <c>{0}</c> in the template is replaced with the entry assembly name (same effect as <c>string.Format</c>, but substitution uses <c>Replace</c> so shell scripts can contain literal braces).</summary>");
		sb.AppendLine("\tpublic static class " + arghGeneratedRootTypeName);
		sb.AppendLine("\t{");

		// Static fields that hold the parsed global/namespace options instances.
		// Commands inject these via method or constructor parameters.
		if (app.GlobalOptionsModel is { } globalOptModel)
		{
			var fq = globalOptModel.TypeFq;
			sb.AppendLine($"\t\tprivate static {fq} {OptionsStaticFieldNameFq(fq)} = new {fq}();");
		}
		foreach ((var nsNode, _) in EnumerateCommandNamespaceNodesWithPath(app.Root, ImmutableArray<string>.Empty))
		{
			if (nsNode.CommandNamespaceOptionsModel is { } nsModel)
			{
				var fq = nsModel.TypeFq;
				sb.AppendLine($"\t\tprivate static {fq} {OptionsStaticFieldNameFq(fq)} = new {fq}();");
			}
		}
		sb.AppendLine();

		EmitCompletionForApp(sb, app);
		sb.AppendLine("\t\tpublic static Task<int> RunAsync(string[] args) =>");
		sb.AppendLine("\t\t\tRunWithCancellationAsync(args);");
		sb.AppendLine();
		AppendRunWithCancellationAsyncMethod(sb);
		EmitRunCoreHierarchical(sb, app, entryAssemblyName);
		sb.AppendLine();
		EmitPrintRootHelpHierarchical(sb, app, entryAssemblyName);
		sb.AppendLine();
		foreach ((var node, var path) in EnumerateCommandNamespaceNodesWithPath(app.Root, ImmutableArray<string>.Empty))
			EmitCommandNamespaceHelpPrinter(sb, path, node, app, entryAssemblyName);

		foreach (var cmd in app.AllCommands)
			EmitCommandHelpPrinter(sb, cmd, app, entryAssemblyName);

		foreach (var cmd in app.AllCommands)
			EmitCommandFlagHelpToStdErrMethod(sb, cmd, app);

		sb.AppendLine("\t\tprivate static void PrintVersion()");
		sb.AppendLine("\t\t{");
		sb.AppendLine($"			Console.Out.WriteLine(\"{Escape(entryAssemblyVersion)}\");");
		sb.AppendLine("\t\t}");
		sb.AppendLine();

		foreach (var cmd in app.AllCommands)
		{
			var injectedOpts = app.InjectionChains.TryGetValue(cmd.RunMethodName, out var precomputed3)
				? precomputed3
				: BuildOptionsInjectionChain(app, cmd);
			EmitCommandRunner(sb, cmd, app.GlobalMiddleware, injectedOptions: injectedOpts, entryAssemblyName: entryAssemblyName);
		}

		{
			var globalPrefetchMembers = CollectRootPrefetchGlobalMembers(app);
			var deferRootPrefetch = CollectDeferredRootAliasPrefetchFlags(app);
			if (globalPrefetchMembers.Length > 0 || deferRootPrefetch.Length > 0)
			{
				if (app.GlobalOptionsModel is { } g)
				{
					EmitOptionsTryParse(sb, "TryParseGlobalOptions",
						globalPrefetchMembers,
						storeTypeFq: g.TypeFq,
						storeFieldName: OptionsStaticFieldNameFq(g.TypeFq),
						storeBestCtorParamOrder: g.BestCtorParamOrder,
						entryAssemblyName: entryAssemblyName,
						deferLeadingRootAliasFlags: deferRootPrefetch);
				}
				else
					EmitOptionsTryParse(sb, "TryParseGlobalOptions", globalPrefetchMembers,
						entryAssemblyName: entryAssemblyName,
						deferLeadingRootAliasFlags: deferRootPrefetch);
			}
		}

		foreach ((var node, var path) in EnumerateCommandNamespaceNodesWithPath(app.Root, ImmutableArray<string>.Empty))
		{
			if (node.CommandNamespaceOptionsModel is { } nsModel)
			{
				// Use FLATTENED members (including inherited) so flags from parent options types are
				// also recognised and consumed between the namespace segment and the sub-command.
				if (nsModel.FlattenedMembers.Length > 0)
					EmitOptionsTryParse(sb, CommandNamespaceOptionsParseMethodName(path), nsModel.FlattenedMembers,
						storeTypeFq: nsModel.TypeFq,
						storeFieldName: OptionsStaticFieldNameFq(nsModel.TypeFq),
						storeBestCtorParamOrder: nsModel.BestCtorParamOrder,
						entryAssemblyName: entryAssemblyName);
			}
		}

		EmitTryParseRouteHierarchical(sb, app);
		EmitIsIntrinsicCommand(sb, app);
		EmitDispatchForNode(sb, app, app.Root, ImmutableArray<string>.Empty, "DispatchRoot", isRoot: true, entryAssemblyName);
		sb.AppendLine("\t\tprivate static bool? ParseNullableBool(string? raw, bool fromYesSwitch)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tif (string.IsNullOrEmpty(raw)) return fromYesSwitch;");
		sb.AppendLine("\t\t\tif (bool.TryParse(raw, out var b)) return b;");
		sb.AppendLine("\t\t\treturn fromYesSwitch;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\tprivate static string[] TailFrom(string[] args, int start)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tif (start >= args.Length) return Array.Empty<string>();");
		sb.AppendLine("\t\t\tvar n = args.Length - start;");
		sb.AppendLine("\t\t\tvar r = new string[n];");
		sb.AppendLine("\t\t\tArray.Copy(args, start, r, 0, n);");
		sb.AppendLine("\t\t\treturn r;");
		sb.AppendLine("\t\t}");
		EmitDtoBindingMethods(sb, dtoTargets);
		sb.AppendLine();
		var schemaVersion = app.SchemaVersionOverride ?? entrySchemaVersion;
		EmitBuildCliSchemaDocumentHierarchical(sb, app, entryAssemblyName, schemaVersion);
		sb.AppendLine("\t}");
		AppendArghRuntimeModuleInitializer(sb, arghGeneratedRootTypeName);
		sb.AppendLine("}");
		context.AddSource("ArghGenerated.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
	}

	private static IEnumerable<(RegistryNode node, ImmutableArray<string> path)> EnumerateCommandNamespaceNodesWithPath(
		RegistryNode root,
		ImmutableArray<string> prefix)
	{
		foreach (var ch in root.Children)
		{
			var p = AppendSegment(prefix, ch.Segment);
			yield return (ch.Node, p);
			foreach ((var node, var sub) in EnumerateCommandNamespaceNodesWithPath(ch.Node, p))
				yield return (node, sub);
		}
	}

	private static string CommandNamespacePathKey(ImmutableArray<string> path)
	{
		if (path.IsDefaultOrEmpty)
			return "Root";

		var sb = new StringBuilder();
		for (var i = 0; i < path.Length; i++)
		{
			if (i > 0)
				sb.Append('_');
			sb.Append(Naming.SanitizeIdentifier(path[i]));
		}

		return sb.ToString();
	}

	private static string CommandNamespaceOptionsParseMethodName(ImmutableArray<string> path) =>
		"TryParseCommandNamespaceOptions_" + CommandNamespacePathKey(path);

	private static void EmitRunCoreHierarchical(StringBuilder sb, AppEmitModel app, string entryAssemblyName)
	{
		var hasLeadingOptionPrefetch =
			CollectRootPrefetchGlobalMembers(app).Length > 0 || CollectDeferredRootAliasPrefetchFlags(app).Length > 0;
		sb.AppendLine("\t\tprivate static async Task<int> RunCoreAsync(string[] args, CancellationToken ct)");
		sb.AppendLine("\t\t{");
		EmitRootCompletionScriptBlock(sb, "\t\t\t", entryAssemblyName);
		EmitRootCompleteBlock(sb, "\t\t\t");
		EmitRootSchemaBlock(sb, "\t\t\t");
		sb.AppendLine("\t\t\tvar idx = new int[1];");
		if (hasLeadingOptionPrefetch)
			sb.AppendLine("\t\t\tif (!TryParseGlobalOptions(args, idx)) return 2;");

		sb.AppendLine("\t\t\tif (idx[0] < args.Length && (args[idx[0]] == \"--help\" || args[idx[0]] == \"-h\"))");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tPrintRootHelp();");
		sb.AppendLine("\t\t\t\treturn 0;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tif (idx[0] < args.Length && args[idx[0]] == \"--version\")");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tPrintVersion();");
		sb.AppendLine("\t\t\t\treturn 0;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tif (idx[0] >= args.Length)");
		sb.AppendLine("\t\t\t{");
		if (app.Root.RootCommand is { } runCoreRoot)
			sb.AppendLine($"\t\t\t\treturn await {runCoreRoot.RunMethodName}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
		else if (app.Root.RootAlias is { } runCoreAlias)
			sb.AppendLine($"\t\t\t\treturn await {runCoreAlias.RunMethodName}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
		else
		{
			sb.AppendLine("\t\t\t\tPrintRootHelp();");
			sb.AppendLine("\t\t\t\treturn 0;");
		}

		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\treturn await DispatchRoot(args, idx, ct).ConfigureAwait(false);");
		sb.AppendLine("\t\t}");
	}

	private static void EmitPrintRootHelpHierarchical(StringBuilder sb, AppEmitModel app, string entryAssemblyName)
	{
		var rootGlobalFlags = new List<ParameterModel>();
		if ((app.Root.RootCommand is not null || app.Root.RootAlias is not null) &&
		    app.GlobalOptionsModel is OptionsTypeModel gomH && gomH.Members.Length > 0)
		{
			foreach (var p in gomH.Members)
			{
				if (p.Kind == ParameterKind.Flag)
					rootGlobalFlags.Add(p);
			}
		}

		var widthCandidatesGlobalRoot = new List<int> { "-h, --help".Length, "--version".Length };
		widthCandidatesGlobalRoot.AddRange(rootGlobalFlags.Select(p => HelpLayout.FormatOptionLeftCell(p).Length));
		var maxOptWidthRoot = Math.Min(widthCandidatesGlobalRoot.Max(), 40);
		maxOptWidthRoot = Math.Max(maxOptWidthRoot, "-h, --help".Length);

		var maxNsListingW = app.Root.Children.Count == 0 ? 0 : app.Root.Children.Max(ch => ch.Segment.Length);
		var visibleRootCmds = app.Root.Commands.Where(static c => !c.IsHidden).ToList();
		var maxCmdListingW = visibleRootCmds.Count == 0 ? 0 : visibleRootCmds.Max(c => c.CommandName.Length);

		sb.AppendLine("\t\tprivate static void PrintRootHelp()");
		sb.AppendLine("\t\t{");
		sb.AppendLine(
			$"\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Usage: \") + CliHelpFormatting.Accent(\"{Escape(entryAssemblyName)}\") + \" <namespace|command> [options]\");");
		sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		if (app.Root.RootCommand is { } rootOverview)
			EmitRootCommandHelpOverview(sb, rootOverview, "\t\t\t", app, entryAssemblyName);
		else if (app.Root.RootAlias is { } rootAliasOverview)
			// Preserve the legacy MapRoot root-help shape: "(default command)" plus handler docs — not the abbreviated
			// root-alias synopsis (those details remain on the named sub-command's --help).
			EmitRootCommandHelpOverview(sb, rootAliasOverview, "\t\t\t", app, entryAssemblyName, includeScopedDefaultHelpOptions: false);
		else if (!string.IsNullOrWhiteSpace(app.RootSummary))
		{
			EmitCommandHelpDocPrologue(sb, "\t\t\t", null, app.RootSummary, false);
			sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		}

		sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Global options:\"));");
		sb.AppendLine(
			$"\t\t\tConsole.Out.WriteLine(\"  \" + CliHelpFormatting.Placeholder(\"{Escape("-h, --help".PadRight(maxOptWidthRoot))}\") + \"  Show help.\");");
		sb.AppendLine(
			$"\t\t\tConsole.Out.WriteLine(\"  \" + CliHelpFormatting.Placeholder(\"{Escape("--version".PadRight(maxOptWidthRoot))}\") + \"  Show version.\");");
		EmitHelpOptionRows(sb, rootGlobalFlags, maxOptWidthRoot);
		sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		if (app.Root.Children.Count > 0)
		{
			sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Namespaces:\"));");
			foreach (var ch in app.Root.Children.OrderBy(ch => ch.Segment, StringComparer.OrdinalIgnoreCase).ThenBy(ch => ch.Segment, StringComparer.Ordinal))
			{
				var sumArg = string.IsNullOrWhiteSpace(ch.SummaryOneLiner)
					? "null"
					: $"\"{Escape(ch.SummaryOneLiner)}\"";
				sb.AppendLine(
					$"\t\t\tCliHelpFormatting.WriteHelpListNameAndDescription(true, \"{Escape(ch.Segment)}\", {sumArg}, {maxNsListingW});");
			}

			sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		}

		if (visibleRootCmds.Count > 0)
		{
			sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Commands:\"));");
			foreach (var c in visibleRootCmds.OrderBy(c => c.CommandName, StringComparer.OrdinalIgnoreCase).ThenBy(c => c.CommandName, StringComparer.Ordinal))
			{
				var sumArg = string.IsNullOrWhiteSpace(c.SummaryOneLiner)
					? "null"
					: $"\"{Escape(c.SummaryOneLiner)}\"";
				sb.AppendLine(
					$"\t\t\tCliHelpFormatting.WriteHelpListNameAndDescription(false, \"{Escape(c.CommandName)}\", {sumArg}, {maxCmdListingW});");
			}
		}

		sb.AppendLine("\t\t}");
	}

	private static void EmitCommandNamespaceHelpPrinter(StringBuilder sb, ImmutableArray<string> path, RegistryNode node, AppEmitModel app, string entryAssemblyName)
	{
		var key = CommandNamespacePathKey(path);
		var usagePrefix = string.Join(" ", path);

		var globalFlagMembers = EnumerateFlagMembers(app.GlobalOptionsModel).ToList();
		List<(string Segment, List<ParameterModel> Rows)> namespaceOptionSections = new();
		var namespaceOptionChain = GetCommandNamespaceOptionChain(app, path);
		var suppressedForNamespaceDisplay = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
		AddCliKeys(globalFlagMembers, suppressedForNamespaceDisplay);
		foreach ((var seg, var gom) in namespaceOptionChain)
		{
			var allInNamespace = EnumerateFlagMembers(gom).ToList();
			var rows = allInNamespace.Where(p => !suppressedForNamespaceDisplay.Contains(p.CliLongName)).ToList();
			AddCliKeys(allInNamespace, suppressedForNamespaceDisplay);
			if (rows.Count > 0)
				namespaceOptionSections.Add((seg, rows));
		}

		var hasNsDoc = !string.IsNullOrWhiteSpace(node.SummaryInnerXml);
		var showGlobalFlagsInNs = (node.RootCommand is not null || hasNsDoc) && globalFlagMembers.Count > 0;
		var showNamespaceScopedOptionSections = node.RootCommand is not null || hasNsDoc;
		var widthCandidatesNs = new List<int> { "-h, --help".Length };
		if (showGlobalFlagsInNs)
			widthCandidatesNs.AddRange(globalFlagMembers.Select(p => HelpLayout.FormatOptionLeftCell(p).Length));
		if (showNamespaceScopedOptionSections)
		{
			foreach ((_, var rows) in namespaceOptionSections)
				widthCandidatesNs.AddRange(rows.Select(p => HelpLayout.FormatOptionLeftCell(p).Length));
		}

		var maxOptWidth = Math.Min(widthCandidatesNs.Max(), 40);
		maxOptWidth = Math.Max(maxOptWidth, "-h, --help".Length);

		var maxChildNsListingW = 0;
		if (node.Children.Count > 0)
			maxChildNsListingW = node.Children.Max(ch => FormatQualifiedCliPath(path, ch.Segment).Length);
		var maxChildCmdListingW = 0;
		var visibleNodeCmds = node.Commands.Where(static c => !c.IsHidden).ToList();
		if (visibleNodeCmds.Count > 0)
			maxChildCmdListingW = visibleNodeCmds.Max(c => FormatQualifiedCliPath(path, c.CommandName).Length);

		sb.AppendLine($"\t\tprivate static void PrintHelp_CommandNamespace_{key}()");
		sb.AppendLine("\t\t{");
		sb.AppendLine(
			$"\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Usage: \") + CliHelpFormatting.Accent(\"{Escape(entryAssemblyName)}\") + \" {Escape(usagePrefix)} <command> [options]\");");
		sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		if (node.RootCommand is { } nsRootOverview)
			EmitRootCommandHelpOverview(sb, nsRootOverview, "\t\t\t", app, entryAssemblyName);
		else if (node.RootAlias is { } nsAliasOverview)
			EmitRootAliasHelpOverview(sb, nsAliasOverview, path, "\t\t\t", entryAssemblyName);
		else if (!string.IsNullOrWhiteSpace(node.SummaryInnerXml))
		{
			EmitCommandHelpDocPrologue(sb, "\t\t\t", node.SummaryInnerXml, "", false);
			sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		}

		sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Global options:\"));");
		sb.AppendLine(
			$"\t\t\tConsole.Out.WriteLine(\"  \" + CliHelpFormatting.Placeholder(\"{Escape("-h, --help".PadRight(maxOptWidth))}\") + \"  Show help.\");");
		if (showGlobalFlagsInNs)
			EmitHelpOptionRows(sb, globalFlagMembers, maxOptWidth);

		sb.AppendLine("\t\t\tConsole.Out.WriteLine();");

		if (showNamespaceScopedOptionSections)
		{
			foreach ((var segment, var gRows) in namespaceOptionSections)
			{
				sb.AppendLine($"\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"'{Escape(segment)}' options:\"));");
				EmitHelpOptionRows(sb, gRows, maxOptWidth);
				sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
			}
		}

		if (node.Children.Count > 0)
		{
			sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Namespaces:\"));");
			foreach (var ch in node.Children.OrderBy(ch => ch.Segment, StringComparer.OrdinalIgnoreCase).ThenBy(ch => ch.Segment, StringComparer.Ordinal))
			{
				var fullNs = FormatQualifiedCliPath(path, ch.Segment);
				var sumArg = string.IsNullOrWhiteSpace(ch.SummaryOneLiner)
					? "null"
					: $"\"{Escape(ch.SummaryOneLiner)}\"";
				sb.AppendLine(
					$"\t\t\tCliHelpFormatting.WriteHelpListNameAndDescription(true, \"{Escape(fullNs)}\", {sumArg}, {maxChildNsListingW});");
			}

			sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
		}

		if (visibleNodeCmds.Count > 0)
		{
			sb.AppendLine("\t\t\tConsole.Out.WriteLine(CliHelpFormatting.Section(\"Commands:\"));");
			foreach (var c in visibleNodeCmds.OrderBy(c => c.CommandName, StringComparer.OrdinalIgnoreCase).ThenBy(c => c.CommandName, StringComparer.Ordinal))
			{
				var fullCmd = FormatQualifiedCliPath(path, c.CommandName);
				var sumArg = string.IsNullOrWhiteSpace(c.SummaryOneLiner)
					? "null"
					: $"\"{Escape(c.SummaryOneLiner)}\"";
				sb.AppendLine(
					$"\t\t\tCliHelpFormatting.WriteHelpListNameAndDescription(false, \"{Escape(fullCmd)}\", {sumArg}, {maxChildCmdListingW});");
			}
		}

		if (node.RootCommand is null && !string.IsNullOrWhiteSpace(node.RemarksInnerXml))
		{
			sb.AppendLine("\t\t\tConsole.Out.WriteLine();");
			EmitNotesSection(sb, "\t\t\t", node.RemarksInnerXml, "");
		}

		sb.AppendLine("\t\t}");
		sb.AppendLine();
	}

	private static void EmitDispatchForNode(
		StringBuilder sb,
		AppEmitModel app,
		RegistryNode node,
		ImmutableArray<string> path,
		string methodName,
		bool isRoot,
		string entryAssemblyName)
	{
		sb.AppendLine($"\t\tprivate static async Task<int> {methodName}(string[] args, int[] idx, CancellationToken ct)");
		sb.AppendLine("\t\t{");
		// Call namespace options parse for any namespace that has a registered options type (even if it only
		// inherits flags from a parent type) so that flags between the namespace segment and the sub-command
		// are consumed correctly.
		if (!isRoot && node.CommandNamespaceOptionsModel is { FlattenedMembers.Length: > 0 })
			sb.AppendLine($"\t\t\tif (!{CommandNamespaceOptionsParseMethodName(path)}(args, idx)) return 2;");

		sb.AppendLine("\t\t\tif (idx[0] >= args.Length)");
		sb.AppendLine("\t\t\t{");
		if (node.RootCommand is { } dispatchRoot)
			sb.AppendLine($"\t\t\t\treturn await {dispatchRoot.RunMethodName}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
		else if (node.RootAlias is { } dispatchAlias)
			sb.AppendLine($"\t\t\t\treturn await {dispatchAlias.RunMethodName}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
		else
		{
			if (isRoot)
				sb.AppendLine("\t\t\t\tPrintRootHelp();");
			else
				sb.AppendLine($"\t\t\t\tPrintHelp_CommandNamespace_{CommandNamespacePathKey(path)}();");

			sb.AppendLine("\t\t\t\treturn 0;");
		}

		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tif (args[idx[0]] == \"--help\" || args[idx[0]] == \"-h\")");
		sb.AppendLine("\t\t\t{");
		if (isRoot)
			sb.AppendLine("\t\t\t\tPrintRootHelp();");
		else
			sb.AppendLine($"\t\t\t\tPrintHelp_CommandNamespace_{CommandNamespacePathKey(path)}();");

		sb.AppendLine("\t\t\t\treturn 0;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t\tvar tok = args[idx[0]];");
		foreach (var cmd in node.Commands)
			EmitOrdinalIgnoreCaseIf(sb, "\t\t\t", "tok", cmd.CommandName, s =>
			{
				s.AppendLine("\t\t\t\tidx[0]++;");
				s.AppendLine($"\t\t\t\treturn await {cmd.RunMethodName}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
			});

		foreach (var ch in node.Children)
		{
			var childPath = AppendSegment(path, ch.Segment);
			var childMethod = "DispatchCommandNamespace_" + CommandNamespacePathKey(childPath);
			EmitOrdinalIgnoreCaseIf(sb, "\t\t\t", "tok", ch.Segment, s =>
			{
				s.AppendLine("\t\t\t\tidx[0]++;");
				s.AppendLine($"\t\t\t\treturn await {childMethod}(args, idx, ct).ConfigureAwait(false);");
			});
		}

		var flagFallbackMethod = node.RootCommand?.RunMethodName ?? node.RootAlias?.RunMethodName;
		if (flagFallbackMethod is not null)
		{
			sb.AppendLine("\t\t\tif (tok.Length > 0 && tok[0] == '-')");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine($"\t\t\t\treturn await {flagFallbackMethod}(TailFrom(args, idx[0]), ct).ConfigureAwait(false);");
			sb.AppendLine("\t\t\t}");
		}

		sb.AppendLine("\t\t\t{");
		EmitFuzzyDispatchDefault(sb, node, path, entryAssemblyName);
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		foreach (var ch in node.Children)
		{
			var childPath = AppendSegment(path, ch.Segment);
			EmitDispatchForNode(sb, app, ch.Node, childPath, "DispatchCommandNamespace_" + CommandNamespacePathKey(childPath), isRoot: false, entryAssemblyName);
		}
	}

	/// <summary>
	/// Extracts the full doc-comment XML from a trivia list.
	/// Works regardless of <c>DocumentationMode</c>: when <c>GenerateDocumentationFile</c> is unset the compiler
	/// uses <c>DocumentationMode.None</c> and stores <c>///</c> lines as plain <c>SingleLineCommentTrivia</c>
	/// rather than structured <c>SingleLineDocumentationCommentTrivia</c>. Both paths are handled here.
	/// </summary>
}
